---
title: "Data Gathering"
author: "Margaret Reed"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-pkgs}
library(tidyverse)
library(janitor)
library(purrr)
```

```{r load-data}
egypt_bank_lending_rate <- read_csv("data/Bank Lending Rate/Bank Lending Rate mo12m change Egypt.csv")
egypt_broad_money <- read_csv("data/Broad Money/broad_money_egypt.csv")
egypt_account_balance_pc <- read_csv("data/Current Account Balance(change% yr over yr)/Egypt_monthly_yroveryr.csv")
egypt_account_balance_gdp <- read_csv("data/Current Account Balance(overGDP)/Egypt_currentovergdp.csv")
egypt_fer_pc <- read_csv("data/Foreign exchange reserve(change% yr over yr)/FER_yryr%_Egypt.csv")
egypt_fer_gdp <- read_csv("data/Foreign exchange reserve(mil USD)overGDP/FER_GDP_ratio_Egypt.csv")
egypt_policy_rate <- read_csv("data/Policy Rate/Policy_Fed_Rate_diff_Egypt.csv")
egypt_portfolio_flows <- read_csv("data/Portfolio Flows/portfolio_flows_egypt.csv")
# can't find REER
egypt_risk_premium <- read_csv("data/Risk Premium/Egypt_riskpremium.csv")
egypt_volatility <- read_csv("data/Stock market volatility/Egypt_Volatility.csv")
egypt_stock_price_mom <- read_csv("data/stock prices/EGX30_mom%change.csv")
egypt_stock_price_24mma <- read_csv("data/stock prices/EGX30_mo24mma_change.csv")
egypt_term_premium <- read_csv("data/Term Premium/Egypt_termpremium.csv")
egypt_money_velocity <- read_csv("data/Velocity of Money/money_velocity_egypt.csv")
```

```{r clean-data}
egypt_bank_lending_rate <- egypt_bank_lending_rate %>%
  clean_names() %>%
  select(date, mo12m_change) %>%
  rename("bank_lending" = mo12m_change) %>%
  mutate(date = as.Date(paste0(date, "-01"), format = "%Y-%m-%d"),
         my = format(date, "%Y-%m")) %>%
  select(my, bank_lending)

egypt_broad_money <- egypt_broad_money %>%
  rename("broad_money" = "mo12m") %>%
  filter(!is.na(broad_money)) %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, broad_money)

egypt_account_balance_pc <- egypt_account_balance_pc %>%
  clean_names() %>%
  rename("account_balance_pc" = "yo_y_pct_change") %>%
  filter(!is.na(account_balance_pc)) %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, account_balance_pc)

egypt_account_balance_gdp <- egypt_account_balance_gdp %>%
  clean_names() %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, current_over_gdp)

egypt_fer_pc <- egypt_fer_pc %>%
  clean_names() %>%
  rename("fer_pc" = "yryr_percent") %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, fer_pc)

egypt_fer_gdp <- egypt_fer_gdp %>%
  clean_names() %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, fer_gdp)

egypt_policy_rate <- egypt_policy_rate %>%
  clean_names() %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, rate_difference)

egypt_portfolio_flows <- egypt_portfolio_flows %>%
  rename("portfolio_flows" = "portfolio_inv") %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, portfolio_flows)

egypt_risk_premium <- egypt_risk_premium %>%
  clean_names() %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, risk_premium)

egypt_volatility <- egypt_volatility %>%
  clean_names() %>%
  select(date, volatility) %>%
  filter(!is.na(volatility)) %>%
  mutate(month = month(date), 
         year = year(date)) %>%
  group_by(month, year) %>%
  summarize(volatility = mean(volatility)) %>%
  ungroup() %>%
  mutate(date = as.Date(paste0(year, "-", month, "-01")),
         my = format(date, "%Y-%m")) %>%
  select(my, volatility)

egypt_stock_price_mom <- egypt_stock_price_mom %>%
  clean_names() %>%
  rename("stock_price_mom" = "mom_percent_change") %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, stock_price_mom)

egypt_stock_price_24mma <- egypt_stock_price_24mma %>%
  clean_names() %>%
  rename("stock_price_24mma" = "mo24mma_percent_change") %>%
  filter(!is.na(stock_price_24mma)) %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, stock_price_24mma)

egypt_term_premium <- egypt_term_premium %>%
  clean_names() %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, term_premium)

egypt_money_velocity <- egypt_money_velocity %>%
  select(date, mo12m) %>%
  rename("money_velocity" = "mo12m") %>%
  filter(!is.na(money_velocity)) %>%
  mutate(my = format(date, "%Y-%m")) %>%
  select(my, money_velocity)
```


```{r join-data}
data_set <- list(egypt_bank_lending_rate, egypt_broad_money, egypt_account_balance_pc, egypt_account_balance_gdp, egypt_fer_pc, egypt_fer_gdp, egypt_policy_rate, egypt_portfolio_flows, egypt_risk_premium, egypt_volatility, egypt_stock_price_mom, egypt_stock_price_24mma, egypt_term_premium, egypt_money_velocity)

egypt_data <- data_set %>%
  reduce(full_join, by="my") %>%
  mutate(date = as.Date(paste0(my, "-01"), format = "%Y-%m-%d")) %>%
  select(date, everything(), -my) %>%
  arrange(date)
```

```{r write-data}
write_csv(egypt_data, "data/egypt_data.csv")
```


