---
title: "Data Cleaning"
author: "Margaret Reed"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
```

```{r}
read_csv("../FCI_app/data/Egypt_DataFrame.csv")
```
```{r}
hungary_fci <- read_csv("../FCI_app/data/hungary_fci.csv") 
poland_fci <- read_csv("../FCI_app/data/poland_fci.csv") 
```
```{r}
hungary_fci <- hugary_fci %>%
  clean_names() %>%
  mutate(
    date = as.Date(paste0(date, "-01"), format = "%Y-%m-%d")
  )
write_csv(hungary_fci, "../FCI_app/data/hungary_fci.csv")
```

```{r}
poland_fci <- poland_fci %>%
  clean_names() %>%
  mutate(
    date = as.Date(paste0(date, "-01"), format = "%Y-%m-%d")
  )
write_csv(poland_fci, "../FCI_app/data/poland_fci.csv")
```

```{r}
imf_fci_hungary_raw <- read_csv("../PCA-module/IMF_FCI_Hungary.csv") %>%
  clean_names()

imf_fci_hungary <- imf_fci_hungary_raw %>%
  clean_names() %>%
  mutate(
    date = as.Date(paste0(date, "-01"), format = "%Y-%m-%d")
  )


hungary_fci <- right_join(imf_fci_hungary, hungary_fci)
write_csv(hungary_fci, "../FCI_app/data/hungary_fci.csv")
```


```{r}
imf_fci_poland_raw <- read_csv("../PCA-module/IMF_FCI_Poland.csv") %>%
  clean_names()

imf_fci_poland <- imf_fci_poland_raw %>%
  clean_names() %>%
  mutate(
    date = as.Date(paste0(date, "-01"), format = "%Y-%m-%d")
  )


poland_fci <- right_join(imf_fci_poland, poland_fci)
write_csv(poland_fci, "../FCI_app/data/poland_fci.csv")
```
```{r}
read_delim("../FCI_app/current_app/data/poland_weights_rounding.txt", delim = " : ", skip = 4, col_names = c("variable", "weight")) %>%
  slice(1:n()-1) %>%
  mutate(variable = str_replace_all(variable, "_", " "))
```


