---
title: "Capstone data source Foreign Exchange Reserve (mil USD)/GDP"
author: "Mingkang Yuan"
date: "2023-10-09"
output: html_document
---


## Hungary Foreign Exchange Reserve (mil USD)/GDP

```{r}
library(tidyverse)
library(janitor)
hungary_reserve = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Foreign exchange reserve(change% yr over yr)/hungary_annually.csv')
hungary_reserve_1 = hungary_reserve %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

hungary_gdp = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/GDP/hungary_GDP.csv')
hungary_gdp_1 = hungary_gdp %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 2)
library(dplyr)
merged_data_hungary <- merge(hungary_reserve_1, hungary_gdp_1, by="Date", all=TRUE)

merged_data_hungary <- merged_data_hungary[!is.na(merged_data_hungary$Close.x) & !is.na(merged_data_hungary$Close.y), ]

merged_data_hungary$Close.x <- as.numeric(as.character(merged_data_hungary$Close.x))
merged_data_hungary$Close.y <- as.numeric(as.character(merged_data_hungary$Close.y))

merged_data_hungary_new = merged_data_hungary %>% mutate(FER_GDP_ratio = Close.x/(Close.y*1000))

#merged_data_hungary$TermPremium <- round(merged_data_hungary$Close.x - merged_data_hungary$Close.y, 2)

col_names <- colnames(merged_data_hungary_new)

col_names[col_names == "Close.x"] <- "FER(mil USD)"
col_names[col_names == "Close.y"] <- "GDP(bil USD)"
colnames(merged_data_hungary_new) <- col_names

merged_data_hungary_new$Date <- as.Date(merged_data_hungary_new$Date, format="%m/%d/%Y")


merged_data_hungary_new <- merged_data_hungary_new %>% arrange(Date)

head(merged_data_hungary_new)

write.csv(merged_data_hungary_new, file = "Hungary_FER_GDP_ratio.csv", row.names = FALSE)

```

## Nigeria Foreign Exchange Reserve (mil USD)/GDP

```{r}
library(tidyverse)
library(janitor)
nigeria_reserve = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Foreign exchange reserve(change% yr over yr)/nigeria_annually.csv')
nigeria_reserve_1 = nigeria_reserve %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

nigeria_gdp = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/GDP/nigeria_GDP.csv')
nigeria_gdp_1 = nigeria_gdp %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 2)
library(dplyr)
merged_data_nigeria <- merge(nigeria_reserve_1, nigeria_gdp_1, by="Date", all=TRUE)

merged_data_nigeria <- merged_data_nigeria[!is.na(merged_data_nigeria$Close.x) & !is.na(merged_data_nigeria$Close.y), ]

merged_data_nigeria$Close.x <- as.numeric(as.character(merged_data_nigeria$Close.x))
merged_data_nigeria$Close.y <- as.numeric(as.character(merged_data_nigeria$Close.y))

merged_data_nigeria_new = merged_data_nigeria %>% mutate(FER_GDP_ratio = Close.x/(Close.y*1000))

#merged_data_hungary$TermPremium <- round(merged_data_hungary$Close.x - merged_data_hungary$Close.y, 2)

col_names <- colnames(merged_data_nigeria_new)

col_names[col_names == "Close.x"] <- "FER(mil USD)"
col_names[col_names == "Close.y"] <- "GDP(bil USD)"
colnames(merged_data_nigeria_new) <- col_names

merged_data_nigeria_new$Date <- as.Date(merged_data_nigeria_new$Date, format="%m/%d/%Y")


merged_data_nigeria_new <- merged_data_nigeria_new %>% arrange(Date)

head(merged_data_nigeria_new)

write.csv(merged_data_nigeria_new, file = "Nigeria_FER_GDP_ratio.csv", row.names = FALSE)

```


## Poland Foreign Exchange Reserve (mil USD)/GDP

```{r}
library(tidyverse)
library(janitor)
poland_reserve = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Foreign exchange reserve(change% yr over yr)/poland_annually.csv')
poland_reserve_1 = poland_reserve %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

poland_gdp = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/GDP/poland_GDP.csv')
poland_gdp_1 = poland_gdp %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 2)
library(dplyr)
merged_data_poland <- merge(poland_reserve_1, poland_gdp_1, by="Date", all=TRUE)

merged_data_poland <- merged_data_poland[!is.na(merged_data_poland$Close.x) & !is.na(merged_data_poland$Close.y), ]

merged_data_poland$Close.x <- as.numeric(as.character(merged_data_poland$Close.x))
merged_data_poland$Close.y <- as.numeric(as.character(merged_data_poland$Close.y))

merged_data_poland_new = merged_data_poland %>% mutate(FER_GDP_ratio = Close.x/(Close.y*1000))

#merged_data_poland$TermPremium <- round(merged_data_poland$Close.x - merged_data_poland$Close.y, 2)

col_names <- colnames(merged_data_poland_new)

col_names[col_names == "Close.x"] <- "FER(mil USD)"
col_names[col_names == "Close.y"] <- "GDP(bil USD)"
colnames(merged_data_poland_new) <- col_names

merged_data_poland_new$Date <- as.Date(merged_data_poland_new$Date, format="%m/%d/%Y")


merged_data_poland_new <- merged_data_poland_new %>% arrange(Date)

head(merged_data_poland_new)

write.csv(merged_data_poland_new, file = "Poland_FER_GDP_ratio.csv", row.names = FALSE)

```


## Romania Foreign Exchange Reserve (mil USD)/GDP

```{r}
library(tidyverse)
library(janitor)
romania_reserve = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Foreign exchange reserve(change% yr over yr)/romania_annually.csv')
romania_reserve_1 = romania_reserve %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

romania_gdp = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/GDP/romania_GDP.csv')
romania_gdp_1 = romania_gdp %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 2)
library(dplyr)
merged_data_romania <- merge(romania_reserve_1, romania_gdp_1, by="Date", all=TRUE)

merged_data_romania <- merged_data_romania[!is.na(merged_data_romania$Close.x) & !is.na(merged_data_romania$Close.y), ]

merged_data_romania$Close.x <- as.numeric(as.character(merged_data_romania$Close.x))
merged_data_romania$Close.y <- as.numeric(as.character(merged_data_romania$Close.y))

merged_data_romania_new = merged_data_romania %>% mutate(FER_GDP_ratio = Close.x/(Close.y*1000))

#merged_data_romania$TermPremium <- round(merged_data_romania$Close.x - merged_data_romania$Close.y, 2)

col_names <- colnames(merged_data_romania_new)

col_names[col_names == "Close.x"] <- "FER(mil USD)"
col_names[col_names == "Close.y"] <- "GDP(bil USD)"
colnames(merged_data_romania_new) <- col_names

merged_data_romania_new$Date <- as.Date(merged_data_romania_new$Date, format="%m/%d/%Y")


merged_data_romania_new <- merged_data_romania_new %>% arrange(Date)

head(merged_data_romania_new)

write.csv(merged_data_romania_new, file = "Romania_FER_GDP_ratio.csv", row.names = FALSE)

```



