---
title: "Capstone data source Term premium"
author: "Mingkang Yuan"
date: "2023-10-01"
output: html_document
---


## Egypt Term premium (2012-current)

```{r}
library(tidyverse)
library(janitor)
egypt_10yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Egypt_10yr_yield.csv')
egypt_10yr_yield_1 = egypt_10yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

egypt_5yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Egypt_5yr_yield.csv')
egypt_5yr_yield_1 = egypt_5yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)
library(dplyr)
merged_data_egypt <- merge(egypt_10yr_yield_1, egypt_5yr_yield_1, by="Date", all=TRUE)

merged_data_egypt <- merged_data_egypt[!is.na(merged_data_egypt$Close.x) & !is.na(merged_data_egypt$Close.y), ]

merged_data_egypt$Close.x <- as.numeric(as.character(merged_data_egypt$Close.x))
merged_data_egypt$Close.y <- as.numeric(as.character(merged_data_egypt$Close.y))

merged_data_egypt$TermPremium <- round(merged_data_egypt$Close.x - merged_data_egypt$Close.y, 2)

col_names <- colnames(merged_data_egypt)

col_names[col_names == "Close.x"] <- "ten_yr"
col_names[col_names == "Close.y"] <- "five_yr"
colnames(merged_data_egypt) <- col_names

merged_data_egypt$Date <- as.Date(merged_data_egypt$Date, format="%m/%d/%Y")


merged_data_egypt <- merged_data_egypt %>% arrange(Date)

head(merged_data_egypt)

write.csv(merged_data_egypt, file = "Egypt_termpremium.csv", row.names = FALSE)

```

## Hungary Term premium (1999-current)

```{r}
library(tidyverse)
library(janitor)
hungary_10yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Hungary_10yr_yield.csv')
hungary_10yr_yield_1 = hungary_10yr_yield %>% select("Ticker","Currency") %>% slice(-1) %>% row_to_names(row_number = 1)

hungary_5yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Hungary_5yr_yield.csv')
hungary_5yr_yield_1 = hungary_5yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)
library(dplyr)
merged_data_hungary <- merge(hungary_10yr_yield_1, hungary_5yr_yield_1, by="Date", all=TRUE)

merged_data_hungary <- merged_data_hungary[!is.na(merged_data_hungary$Close.x) & !is.na(merged_data_hungary$Close.y), ]

merged_data_hungary$Close.x <- as.numeric(as.character(merged_data_hungary$Close.x))
merged_data_hungary$Close.y <- as.numeric(as.character(merged_data_hungary$Close.y))

merged_data_hungary$TermPremium <- round(merged_data_hungary$Close.x - merged_data_hungary$Close.y, 2)

col_names <- colnames(merged_data_hungary)

col_names[col_names == "Close.x"] <- "ten_yr"
col_names[col_names == "Close.y"] <- "five_yr"
colnames(merged_data_hungary) <- col_names

merged_data_hungary$Date <- as.Date(merged_data_hungary$Date, format="%m/%d/%Y")


merged_data_hungary <- merged_data_hungary %>% arrange(Date)

head(merged_data_hungary)

write.csv(merged_data_hungary, file = "Hungary_termpremium.csv", row.names = FALSE)

```

## Nigeria Term premium (only have 10 year yield)

```{r}
library(tidyverse)
library(janitor)
nigeria_10yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Nigeria_10yr_yield.csv')
nigeria_10yr_yield_1 = nigeria_10yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)


```


## Poland Term premium (2003-2023.3)

```{r}
library(tidyverse)
library(janitor)
poland_10yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Poland_10yr_yield.csv')
poland_10yr_yield_1 = poland_10yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

poland_5yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Poland_5yr_yield.csv')
poland_5yr_yield_1 = poland_5yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)
library(dplyr)
merged_data_poland <- merge(poland_10yr_yield_1, poland_5yr_yield_1, by="Date", all=TRUE)

merged_data_poland <- merged_data_poland[!is.na(merged_data_poland$Close.x) & !is.na(merged_data_poland$Close.y), ]

merged_data_poland$Close.x <- as.numeric(as.character(merged_data_poland$Close.x))
merged_data_poland$Close.y <- as.numeric(as.character(merged_data_poland$Close.y))

merged_data_poland$TermPremium <- round(merged_data_poland$Close.x - merged_data_poland$Close.y, 2)

col_names <- colnames(merged_data_poland)

col_names[col_names == "Close.x"] <- "ten_yr"
col_names[col_names == "Close.y"] <- "five_yr"
colnames(merged_data_poland) <- col_names

merged_data_poland$Date <- as.Date(merged_data_poland$Date, format="%m/%d/%Y")


merged_data_poland <- merged_data_poland %>% arrange(Date)

head(merged_data_poland)

write.csv(merged_data_poland, file = "Poland_termpremium.csv", row.names = FALSE)

```


## Romania Term premium (2008-2022)

```{r}
library(tidyverse)
library(janitor)
romania_10yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Romania_10yr_yield.csv')
romania_10yr_yield_1 = romania_10yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)

romania_5yr_yield = read.csv('/Users/yuanmingkang/Desktop/Fall_24/Capstone/data source/Romania_5yr_yield.csv')
romania_5yr_yield_1 = romania_5yr_yield %>% select("Ticker","Series.Type") %>% slice(-1) %>% row_to_names(row_number = 1)
library(dplyr)
merged_data_romania <- merge(romania_10yr_yield_1, romania_5yr_yield_1, by="Date", all=TRUE)

merged_data_romania <- merged_data_romania[!is.na(merged_data_romania$Close.x) & !is.na(merged_data_romania$Close.y), ]

merged_data_romania$Close.x <- as.numeric(as.character(merged_data_romania$Close.x))
merged_data_romania$Close.y <- as.numeric(as.character(merged_data_romania$Close.y))

merged_data_romania$TermPremium <- round(merged_data_romania$Close.x - merged_data_romania$Close.y, 2)

col_names <- colnames(merged_data_romania)

col_names[col_names == "Close.x"] <- "ten_yr"
col_names[col_names == "Close.y"] <- "five_yr"
colnames(merged_data_romania) <- col_names

merged_data_romania$Date <- as.Date(merged_data_romania$Date, format="%m/%d/%Y")


merged_data_romania <- merged_data_romania %>% arrange(Date)

head(merged_data_romania)

write.csv(merged_data_romania, file = "Romania_termpremium.csv", row.names = FALSE)

```

